name: Deploy Contentful App (main branch only)

on:
  workflow_dispatch:
    inputs:
      app_folder:
        description: 'Which app folder to deploy'
        required: true
        default: 'sidebar-cachepurge-button'
        type: choice
        options:
          - sidebar-cachepurge-button
          - sidebar-release-trigger-button
          - sidebar-stats-panel
      env_target:
        description: 'Environment'
        required: true
        default: 'master'
        type: choice
        options:
          - develop
          - master

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-contentful-apps-common.yaml
    with:
      app_folder: ${{ inputs.app_folder }}
      env_target: ${{ inputs.env_target }}
    secrets: inherit