name: Common Deploy Workflow for Contentful Apps

on:
  workflow_call:
    inputs:
      app_folder:
        required: true
        type: string
      env_target:
        required: true
        type: string
    secrets:
      required:
        - ACCESS_TOKEN
        - ORGANIZATION_ID
        - APP_DEFINITION_ID_PRD_sidebar_cachepurge_button
        - APP_DEFINITION_ID_DEV_sidebar_cachepurge_button
        - APP_DEFINITION_ID_PRD_sidebar_release_trigger_button
        - APP_DEFINITION_ID_DEV_sidebar_release_trigger_button
        - APP_DEFINITION_ID_PRD_sidebar_stats_panel
        - APP_DEFINITION_ID_DEV_sidebar_stats_panel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
        working-directory: ./${{ inputs.app_folder }}

      - name: Build app
        run: npm run build
        working-directory: ./${{ inputs.app_folder }}

      - name: Set App Definition ID
        id: set-app
        run: |
          echo "Determining app definition ID"

          app_folder="${{ inputs.app_folder }}"
          app_folder_env="${app_folder//-/_}"
          env_target="${{ inputs.env_target }}"

          if [[ "$env_target" == "master" ]]; then
            key="APP_DEFINITION_ID_PRD_${app_folder_env}"
          else
            key="APP_DEFINITION_ID_DEV_${app_folder_env}"
          fi

          echo "Resolved secret key: $key"

          app_definition_id="${!key}"
          echo "app_definition_id=$app_definition_id" >> $GITHUB_OUTPUT
        env:
          APP_DEFINITION_ID_PRD_sidebar_cachepurge_button: ${{ secrets.APP_DEFINITION_ID_PRD_sidebar_cachepurge_button }}
          APP_DEFINITION_ID_DEV_sidebar_cachepurge_button: ${{ secrets.APP_DEFINITION_ID_DEV_sidebar_cachepurge_button }}
          APP_DEFINITION_ID_PRD_sidebar_release_trigger_button: ${{ secrets.APP_DEFINITION_ID_PRD_sidebar_release_trigger_button }}
          APP_DEFINITION_ID_DEV_sidebar_release_trigger_button: ${{ secrets.APP_DEFINITION_ID_DEV_sidebar_release_trigger_button }}
          APP_DEFINITION_ID_PRD_sidebar_stats_panel: ${{ secrets.APP_DEFINITION_ID_PRD_sidebar_stats_panel }}
          APP_DEFINITION_ID_DEV_sidebar_stats_panel: ${{ secrets.APP_DEFINITION_ID_DEV_sidebar_stats_panel }}

      - name: Deploy to Contentful
        uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ secrets.ORGANIZATION_ID }}
          app-definition-id: ${{ steps.set-app.outputs.app_definition_id }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          folder: ./${{ inputs.app_folder }}/dist