name: Develop Env - Deploy Contentful Apps

on:
  workflow_dispatch:
    inputs:
      app_folder:
        description: 'Which app folder to deploy'
        required: true
        default: 'sidebar-cachepurge-button'
        type: choice
        options:
          - sidebar-cachepurge-button
          - sidebar-release-trigger-button
          - sidebar-stats-panel

      env_target:
        description: 'Which Contentful environment to deploy to'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.verify.outputs.proceed }}
    steps:
      - name: Verify branch
        id: verify
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "develop" ]] || [[ "${{ github.ref_name }}" =~ ^feature/ ]]; then
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "This workflow is restricted to 'develop' and 'feature/*' branches. Exiting."
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  deploy:
    needs: check-branch
    if: needs.check-branch.outputs.proceed == 'true'
    uses: ./.github/workflows/deploy-contentful-apps-common.yaml
    with:
      app_folder: ${{ github.event.inputs.app_folder }}
      env_target: ${{ github.event.inputs.env_target }}
    secrets: inherit