name: Deploy Contentful App (develop/feature branches)

on:
  workflow_dispatch:
    inputs:
      app_folder:
        description: 'Which app folder to deploy'
        required: true
        default: 'sidebar-cachepurge-button'
        type: choice
        options:
          - sidebar-cachepurge-button
          - sidebar-release-trigger-button
          - sidebar-stats-panel
      env_target:
        description: 'Environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop

jobs:
  deploy:
    if: |
      startsWith(github.ref, 'refs/heads/develop') ||
      startsWith(github.ref, 'refs/heads/feature/')
    uses: ./.github/workflows/deploy-contentful-apps-common.yaml
    with:
      app_folder: ${{ inputs.app_folder }}
      env_target: ${{ inputs.env_target }}
    secrets: inherit